import React from "react";

const Policy = () => {
  return (
    <div className="mx-auto max-w-7xl space-y-1 px-4 py-2">
      <h1 className="font-bold text-2xl">Privacy Policy</h1>
      <p className="font-normal text-base">
        Our Privacy Policy was last updated on October 9, 2022 This Privacy
        Policy describes Our policies and procedures on the collection, use and
        disclosure of Your information when You use the Service and tells You
        about Your privacy rights and how the law protects You. We use Your
        Personal data to provide and improve the Service. By using the Service,
        You agree to the collection and use of information in accordance with
        this Privacy Policy. This Privacy Policy was generated by TermsFeed GDPR
        Privacy Policy Generator .
      </p>

      <h1 className="font-bold text-2xl">Interpretation and Definitions</h1>
      <h2 className="font-semibold text-2xl">Interpretation</h2>
      <p className="font-normal text-base">
        The words of which the initial letter is capitalized have meanings
        defined under the following conditions. The following definitions shall
        have the same meaning regardless of whether they appear in singular or
        in plural.
      </p>
    </div>
  );
};

export default Policy;
