# Generated by Django 4.2 on 2023-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0009_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face_Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('image', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='client_admin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='safty_secruity_policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
