# Generated by Django 4.2 on 2023-12-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0010_face_login_alter_usermodel_client_admin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face_login',
            name='image',
            field=models.BinaryField(),
        ),
    ]
