# Generated by Django 5.0.2 on 2024-04-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0012_rename_country_account_eventid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='login_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('current_task', models.CharField(max_length=300)),
            ],
        ),
    ]
