# Generated by Django 5.0.4 on 2024-05-21 05:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('info', models.TextField()),
                ('document', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mobile_sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=20)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('sms', models.IntegerField(null=True)),
                ('expiry', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RandomSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionID', models.CharField(max_length=2000)),
                ('username', models.CharField(max_length=2000)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
